begin;
select plan(8);
select has_schema('supasync');
select has_table('supasync','files','canonical files exist');
select has_table('supasync','revisions','immutable journal exists');
select has_table('supasync','mutation_receipts','mutation receipts exist');
select ok((select bool_and(relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='supasync' and relkind='r'),'canonical tables use RLS');
set local role anon;
select throws_ok($$select supasync.list_vaults()$$,'42501');
reset role;
set local role authenticated;
select throws_ok($$select supasync.list_vaults()$$,'42501','PERMISSION_DENIED');
reset role;
select ok(not has_table_privilege('supasync_hermes','supasync.revisions','UPDATE'),'Hermes cannot rewrite history');
select * from finish();
rollback;
