begin;
select plan(7);
select has_schema('supasync_v2');
select has_function('public','supasync_v2_rpc',array['text','uuid','jsonb','uuid']);
select has_table('supasync_v2','receipts','receipts table exists');
select has_table('supasync_v2','revisions','revision journal exists');
select ok((select bool_and(c.relrowsecurity) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='supasync_v2' and c.relkind='r'),'All private tables have RLS');
set local role authenticated;
select throws_ok($$select public.supasync_v2_rpc('list_vaults',null,'{}',null)$$,'42501');
reset role;
set local role anon;
select throws_ok($$select public.supasync_v2_rpc('list_vaults',null,'{}',null)$$,'42501');
reset role;
select * from finish();
rollback;
