import esbuild from "esbuild";
import process from "process";
import { builtinModules } from "node:module";
import { copyFile, mkdir } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
SupaSync — source is in the repository, not this file.
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtinModules,
  ],
  format: "cjs",
  target: "es2021",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
  platform: "browser",
});

if (prod) {
  await context.rebuild();
  await context.dispose();
  const output = new URL("../../dist/obsidian/", import.meta.url);
  await mkdir(output, { recursive: true });
  for (const file of ["main.js", "manifest.json", "styles.css", "versions.json"]) {
    await copyFile(new URL(file, import.meta.url), new URL(file, output));
  }
  console.log(`Installable plugin: ${fileURLToPath(output)}`);
} else {
  await context.watch();
}
